default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tpush
  password: tpush

development:
  <<: *default
  database: engine_money_development

test:
  <<: *default
  database: engine_money_test

production:
  <<: *default
  database: engine_money_production
  username: engine_money
  password: <%= ENV['ENGINE_MONEY_DATABASE_PASSWORD'] %>
